import { AppRole } from '../utils/authSession'

export const ROLE_WALLET_MAP: Partial<Record<AppRole, string>> = {
  participant: 'GBCXILQFWSIWZGLEUSCLPQJNBZ2GILW3WMGSALDYN4PBL5VPQOBRXAQ6',
  sponsor: 'GDZEOLYUIF4SHIV2LAN6SDNTN5WIIB4T2436S4E5QOY4XMNSVTGRLAOL',
  organizer: 'GBQTXTNRLKN7JOXQ72AAG73JS2RGIUEYY6ALGN3BXQKWNVMS5WW3E7J2',
}
